name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:_rr)
variables:
  ContainerTag: latest
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .gcloudignore
jobs:
- job: Build
  steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Container'
    inputs:
      containerRegistry: 'mdbtechtest-acr'
      repository: mdbapi2019
      Dockerfile: dockerfile
      tags: $(ContainerTag)